import type { MCQQuestion } from "./types";

export const QUESTION_BANK: MCQQuestion[] = [
  {
    id: "math-01",
    subject: "Math",
    topic: "Algebra",
    question: "If 3x + 5 = 20, what is x?",
    options: ["3", "5", "7", "15"],
    correctIndex: 1,
    explanation: "Subtract 5 from both sides to get 3x = 15, then divide by 3 to get x = 5.",
  },
  {
    id: "math-02",
    subject: "Math",
    topic: "Percent",
    question: "What is 25% of 320?",
    options: ["40", "64", "80", "96"],
    correctIndex: 2,
    explanation: "25% is 1/4, and one-fourth of 320 is 80.",
  },
  {
    id: "math-03",
    subject: "Math",
    topic: "Geometry",
    question: "The sum of interior angles of a triangle is:",
    options: ["90 degrees", "180 degrees", "270 degrees", "360 degrees"],
    correctIndex: 1,
    explanation: "Every triangle has interior angles that add up to 180 degrees.",
  },
  {
    id: "math-04",
    subject: "Math",
    topic: "Ratio",
    question: "If A:B = 2:3 and B = 30, then A is:",
    options: ["15", "20", "25", "45"],
    correctIndex: 1,
    explanation: "If 3 parts = 30, 1 part = 10, so A = 2 parts = 20.",
  },
  {
    id: "math-05",
    subject: "Math",
    topic: "Number",
    question: "What is the LCM of 6 and 8?",
    options: ["12", "18", "24", "48"],
    correctIndex: 2,
    explanation: "Multiples of 6 are 6, 12, 18, 24. Multiples of 8 are 8, 16, 24. First common multiple is 24.",
  },
  {
    id: "science-01",
    subject: "Science",
    topic: "Physics",
    question: "What is the SI unit of force?",
    options: ["Joule", "Newton", "Pascal", "Watt"],
    correctIndex: 1,
    explanation: "Force is measured in Newton (N).",
  },
  {
    id: "science-02",
    subject: "Science",
    topic: "Biology",
    question: "Which organ pumps blood in the human body?",
    options: ["Lungs", "Brain", "Heart", "Kidney"],
    correctIndex: 2,
    explanation: "The heart circulates blood through the body.",
  },
  {
    id: "science-03",
    subject: "Science",
    topic: "Chemistry",
    question: "pH value less than 7 indicates:",
    options: ["Neutral", "Basic", "Acidic", "Salty"],
    correctIndex: 2,
    explanation: "A pH below 7 represents an acidic substance.",
  },
  {
    id: "science-04",
    subject: "Science",
    topic: "Astronomy",
    question: "Earth revolves around:",
    options: ["Moon", "Mars", "Sun", "Jupiter"],
    correctIndex: 2,
    explanation: "Earth orbits the Sun once every year.",
  },
  {
    id: "science-05",
    subject: "Science",
    topic: "Physics",
    question: "Speed is distance divided by:",
    options: ["Mass", "Time", "Volume", "Force"],
    correctIndex: 1,
    explanation: "Speed = Distance / Time.",
  },
  {
    id: "english-01",
    subject: "English",
    topic: "Grammar",
    question: "Choose the correct sentence:",
    options: [
      "She go to school every day.",
      "She goes to school every day.",
      "She going to school every day.",
      "She gone to school every day.",
    ],
    correctIndex: 1,
    explanation: "For third-person singular in present simple, use 'goes'.",
  },
  {
    id: "english-02",
    subject: "English",
    topic: "Vocabulary",
    question: "Synonym of 'rapid' is:",
    options: ["Slow", "Fast", "Weak", "Late"],
    correctIndex: 1,
    explanation: "'Rapid' means very fast.",
  },
  {
    id: "english-03",
    subject: "English",
    topic: "Parts of Speech",
    question: "In the sentence 'He is very smart', the word 'smart' is a:",
    options: ["Verb", "Noun", "Adjective", "Adverb"],
    correctIndex: 2,
    explanation: "'Smart' describes 'he', so it is an adjective.",
  },
  {
    id: "english-04",
    subject: "English",
    topic: "Tense",
    question: "Which is in past tense?",
    options: ["I eat rice.", "I am eating rice.", "I ate rice.", "I will eat rice."],
    correctIndex: 2,
    explanation: "'Ate' is the past form of 'eat'.",
  },
  {
    id: "english-05",
    subject: "English",
    topic: "Comprehension",
    question: "A main idea sentence usually tells:",
    options: [
      "A minor detail",
      "The central point of a paragraph",
      "A difficult word",
      "A grammar mistake",
    ],
    correctIndex: 1,
    explanation: "The main idea states what the paragraph is mostly about.",
  },
  {
    id: "ict-01",
    subject: "ICT",
    topic: "Computer Basics",
    question: "CPU stands for:",
    options: [
      "Central Processing Unit",
      "Computer Personal Unit",
      "Control Program Utility",
      "Central Program User",
    ],
    correctIndex: 0,
    explanation: "CPU is short for Central Processing Unit.",
  },
  {
    id: "ict-02",
    subject: "ICT",
    topic: "Networking",
    question: "WWW means:",
    options: [
      "World Wide Web",
      "World Web Window",
      "Wide World Wire",
      "Web World Work",
    ],
    correctIndex: 0,
    explanation: "WWW stands for World Wide Web.",
  },
  {
    id: "ict-03",
    subject: "ICT",
    topic: "Storage",
    question: "Which device is used for long-term data storage?",
    options: ["RAM", "Hard Disk", "Cache", "Register"],
    correctIndex: 1,
    explanation: "Hard disk/SSD stores data persistently.",
  },
  {
    id: "ict-04",
    subject: "ICT",
    topic: "Security",
    question: "A strong password should contain:",
    options: [
      "Only lowercase letters",
      "Only numbers",
      "Mix of letters, numbers, and symbols",
      "Your name and birth year",
    ],
    correctIndex: 2,
    explanation: "A mixed and unique password is harder to guess.",
  },
  {
    id: "ict-05",
    subject: "ICT",
    topic: "Software",
    question: "Which one is an operating system?",
    options: ["MS Word", "Google Chrome", "Windows 11", "PowerPoint"],
    correctIndex: 2,
    explanation: "Windows 11 is an operating system.",
  },
];
