import type { MCQQuestion } from "./types";

export const QUESTION_BANK: MCQQuestion[] = [
  {
    id: "bcs-bangla-hard-01",
    subject: "Bengali Language and Literature",
    language: "Bengali",
    difficulty: "Hard",
    syllabusPart: 1,
    topic: "Bangla Literature",
    question: "চর্যাপদের ভাষাকে সন্ধ্যা ভাষা বলা হয় কেন?",
    options: [
      "এটি সম্পূর্ণ সংস্কৃত নির্ভর",
      "অর্থ আংশিক গোপন ও প্রতীকী",
      "এটি কেবল সন্ধ্যায় পাঠ করা হতো",
      "এতে কোনো প্রাকৃত প্রভাব নেই",
    ],
    correctIndex: 1,
    explanation: "চর্যাপদের ভাষা প্রতীকী ও গুপ্তার্থপূর্ণ হওয়ায় একে সন্ধ্যা ভাষা বলা হয়।",
  },
  {
    id: "bcs-english-hard-01",
    subject: "English Language and Literature",
    language: "English",
    difficulty: "Hard",
    syllabusPart: 2,
    topic: "Grammar",
    question: "Which sentence correctly uses inversion after a negative adverbial?",
    options: [
      "Rarely he has faced such criticism.",
      "Rarely has he faced such criticism.",
      "Rarely he faced has such criticism.",
      "Rarely has faced he such criticism.",
    ],
    correctIndex: 1,
    explanation: "Negative adverbials at the beginning trigger auxiliary-subject inversion.",
  },
  {
    id: "bcs-math-hard-01",
    subject: "Mathematical Reasoning",
    language: "English",
    difficulty: "Hard",
    syllabusPart: 3,
    topic: "Number Theory",
    question: "If n leaves remainders 2, 3, and 4 when divided by 5, 7, and 9 respectively, what is the least possible n?",
    options: ["157", "247", "312", "472"],
    correctIndex: 0,
    explanation: "157 gives remainders 2, 3, and 4 when divided by 5, 7, and 9 respectively.",
  },
  {
    id: "bcs-ict-hard-01",
    subject: "Computer Science",
    language: "English",
    difficulty: "Hard",
    syllabusPart: 4,
    topic: "Networking",
    question: "Which OSI layer is responsible for end-to-end reliable delivery using sequencing and acknowledgements?",
    options: ["Network", "Transport", "Session", "Data Link"],
    correctIndex: 1,
    explanation: "The transport layer provides end-to-end delivery features such as reliability, sequencing, and acknowledgements.",
  },
];
